# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    api_paypal: 'https://api-3t.sandbox.paypal.com/nvp?'
    api_paypal_version: 56.0
    paypal_user: 'vendeur_api1.threeshells.ovh'
    paypal_pwd: 'WQKME4VX9SHK94UD'
    paypal_signature: 'AKNk88YmgHwBD55a4ZioyXiB6iLJAzZ8Cc1U9.HJ6eVKNXhNpGV.lWHq'

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
